### ISSUE TITLE
Public resources day4 widget error

### ISSUE THREAD

**Issue by pwalczysko** [ome/EMBL-EBI-imaging-course-04-2024#1]
In the cell of the ``Public_Resources.ipynb`` notebook: 
The cell does not display image, instead, error is thrown as below. Repeated on Mac M1 locally as well as on Linux provided machine from the course.  cc @jburel 

```
# Display the images
from ipywidgets import AppLayout, widgets

table_widget = widgets.HTML("")

html = "<table>"
for gene in development_stage:
    images = development_stage[gene]
    if len(images) > 0:
        html += '<tr><td><h2>Gene: '+gene+'</h2></td></tr><tr>'
        for k, v in images:
            html += '<tr><td><h4>Developmental stage: '+k+'</h4></td></tr><tr>'
            for i in v:
                qs = {'id': i}
                url = IMAGE_DATA_URL.format(**qs)
                url_link = LINK_URL.format(**qs)
                html += '<td><a href="'+url_link+'" target="_blank"><img src="'+url+'"/></a></td>'
            html += "</tr>"
        html += "</tr>"
html += "</table>"

table_widget.value = html
AppLayout(header=None,
          left_sidebar=None,
          center=table_widget,
          right_sidebar=None,
          footer=None)
```
Response

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'GridBoxModel' from module '@jupyter-widgets/controls'
loadClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.fe2572ece3b7955c89bb.js?v=fe2572ece3b7955c89bb:1:75054
loadModelClass@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.0a90bd910629a565bb7e.js?v=0a90bd910629a565bb7e:1:10728
_make_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.0a90bd910629a565bb7e.js?v=0a90bd910629a565bb7e:1:7516
new_model@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.0a90bd910629a565bb7e.js?v=0a90bd910629a565bb7e:1:5136
handle_comm_open@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.0a90bd910629a565bb7e.js?v=0a90bd910629a565bb7e:1:3893
134/v/this._handleCommOpen@http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.fe2572ece3b7955c89bb.js?v=fe2572ece3b7955c89bb:1:73470
_handleCommOpen@http://localhost:8888/static/notebook/3676.bundle.js:1:30934
```

**Comment by pwalczysko** [comment]
It seems that this error is repeating on all cells with start with ``import ipywidgets`` or ``from impywidgets import *``

The notebooks which have this error:
``Reading_images.ipynb`` (2 places) - correction - this notebook is supposed to run from the cellpose env, and when done so, **it does not have the "widgets" problem**
``Public_Resources.ipynb`` (3 places) - this notebook is supposed to run from the ``Day_4/environment.yml`` (it cannot be run from the cellpose env, as there is no ``intermine`` module installed) and when done so, **it still shows the problem**

It seems that any cell which has the word ``widget`` inside and is supposed to display an image is failing.

**Comment by pwalczysko** [comment]
I would suggest 2 points:

1. Clearly state on the Public_Resources.ipynb, in an extra well visible cell, from which env it is supposed to be run (I think it is ``environment.yml`` but it is very easy to be mistaken).
2. Check all the cells in Public_Resources.ipynb which attempt to display an image and have the word "widget" in them - these cells do not wfm, they display errors as shown in the header of this PR.

**Comment by pwalczysko** [comment]
Note: PublicResources.ipynb are working fine on Google Colab.

**Comment by jburel** [comment]
See https://github.com/ome/EMBL-EBI-imaging-course-04-2024/pull/10
