### ISSUE TITLE
stardist Day_4 on linux VM

### ISSUE THREAD

**Issue by pwalczysko** [ome/EMBL-EBI-imaging-course-04-2024#3]
After successful build, execute the first cell with imports  - note, as this error is occurring only on the Linux VM and does not repeat on the local M1 (which runs stardist Day_4 as expected), I cannot copy and paste the error from the remote desktop client, hence the screenshot.

![Screenshot 2024-04-10 at 17 29 27](https://github.com/ome/EMBL-EBI-imaging-course-04-2024/assets/2478303/21f0857b-8e60-4fdc-bf8a-45bc7f1b1eef)

**Comment by pwalczysko** [comment]
note stardist day 4 wfm in g colab and locally on M1

**Comment by jburel** [comment]
Which version of openssl is installed?

**Comment by pwalczysko** [comment]
> Which version of openssl is installed?

Do not know the answer as the VM is not available anymore. I am told by the admin of the VM that this issue is fixed.

**Comment by jburel** [comment]
This is fixed
