### ISSUE TITLE
Reading images day 5 %%time

### ISSUE THREAD

**Issue by pwalczysko** [ome/EMBL-EBI-imaging-course-04-2024#4]
The notebook reading images day 5 wfm except for the cell

```
# Do not run this cell in Google Colab
%%time
image_location = 'images/mri.ome.zarr/s0'
data = load_binary_from_local_with_data(image_location)
print(data.shape)
```
Response

``UsageError: Line magic function `%%time` not found.``

Can we remove or replace ?

**Comment by jburel** [comment]
Fixed see https://github.com/ome/EMBL-EBI-imaging-course-04-2024/pull/11
